batch_size: 256
batches_per_allreduce: 1
data_location: /data/imagenet
dataset: imagenet
epochs: 90
fp16_allreduce: false
gpu: 'true'
gradient_predivide_factor: 1.0
label: base
log_interval: 100
lr: 0.1
model: resnet18
momentum: 0.9
weight_decay: 0.0001
num_workers: 32
restart: false
seed: 2021
use_adasum: false
loss: cross_entropy
date: "2021-02-20"