batch_size: 128
batches_per_allreduce: 1
data_location: /data/imagenet
dataset: imagenet
epochs: 90
fp16_allreduce: false
gpu: 'true'
gradient_predivide_factor: 1.0
label: base
log_interval: 100
lr: 0.0125
model: resnet101
momentum: 0.5
num_workers: 16
restart: false
seed: 2021
use_adasum: false
loss: cross_entropy
date: "2021-02-16"
